language: java
jdk:
- openjdk11
before_script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=indrabasak-github
  -Dsonar.login=$SONAR_TOKEN
cache:
  directories: "– $HOME/.m2 – $HOME/.sonar/cache"
notifications:
  email:
  - indra.basak1@gmail.com
  on_success: change
  on_failure: always
  use_notice: true
env:
  global:
  - secure: EVY4dWcEV5YLwAZ8raYvcM3eZoE2kVr7k/bW+KZtCHhSBSqTsOo7Op89iExo/fCI35b5TWZPj+XctYYUqgARP/IsX6o/L6Akk02hZbKW6fTPdStStY1xlIJjQllvpwxyQ/ICObeYZu8sAoEFcurlCoh1RhJUz4I5OoGIvyVWBa+BLZWC+ob/+sRiJXTLKuP/1pralashNY9SGlR/GLd1kI8A7EN46XnlSJQOSxeKHQqQXHvbU4Ua6G3JBc7jOKqYq/JckuU36JUu8WHHwMgIPmevwAsj73WqQZ0PVGwlBje/fCPXjZsN8zzq4yIyjazswWdZG7DT3vWQjB9GENyLB5ldelqGxDGCsDx/UuUttlXhCLTTcCOJCKXdkrtxPhXFG4TMDT9bSr9v7X8Ydkce4tROdAi892+mgmRfM7vKlO9l7cycUxwQzEXirUUMlGNXGlePgQMusBPiKXANZ9KeCLnBo4JL/jlpLagPpCo1xf7UygTS+frpg2wvmwZl3fhTxE+D0hDImaKv5cdVtxytnn79o4ZlwlpqixatEieC09TuKhqx/+W7/U++4rpl7Aiu78NzI1RUkALPGZQe+iXHyjKa8AzgIdhqY0vmHcnouhajZsUsFWYn6najTZRuTIb+wGjf9JjhgG64AK7JvNM0TFFlHIJOT+SGIr7qDfeS3xU=
