language: java
jdk:
  - openjdk11
before_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=indrabasak-github -Dsonar.login=$SONAR_TOKEN
cache:
  directories: "– $HOME/.m2 – $HOME/.sonar/cache"
notifications:
  email:
    - indra.basak1@gmail.com
  on_success: change
  on_failure: always
  use_notice: true
env:
  global:
    secure: NSiU2BQN7xsJH23BG7jjcny/8QiAxbvF40VOBcR7k/oO9RyhYyWVAftRDRoBZF/TklNBxvmVD/TIZAmfzHFS+5bJSF1iZiKREESvJbd4eRPQTy1wLr0gG8n4PNaqeOEcblhmik8J/e+TQQUKUcS1mpvJOsYp3ngq72YRO/5Ein7LMUChkTqA9Hlo65H6RHL5MV4tu8xzmhjaw9kIvDIIarR3Vx56Iq1fKMHJu7/L8mqI+mDnAuqENGcAMF/B1YKk4DMnwxoGdCUHGnJ5go+1ZL0J7Uw2FYNT9tE70MyNGV20mzPUHVFb6CNhPvcCSK93QkYjlmoy9uAmZbWC4pKmf1yTf+vyCQzsWB3XWQMqLFL3XX9NyPoiNe6CvBVUmwM0GKJ3c0LWkdknWH4Q7IPJdDhYXD1q0k08HJ5A4QP90rDRFD8Y/nmoaTy2you/iNkZe2DPMMssFBRI2HT8TTIr/Yb68Ykg/OxAQU/udAUNpcIUFVXctOPvELSbOiFzkdI/3x5ZxJ+NjIOGHVWlKwyZTf+1w+6F9yep8QC9WMU6ncAtOPYyULP7tMSKgluSzRhfUm/zEnxTaM9jIkQwXOfjC0Z3nunKjmhRwmUkPnLfReKzbhyXNAwT9kfME8ojb2rLbqZyTPo70pC84VM1iy4SBt/jtwEFD18tjg5Ml8jXneE=
