language: java
jdk:
- oraclejdk8
before_script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=indrabasak-github
  -Dsonar.login=$SONAR_TOKEN
cache:
  directories: "– $HOME/.m2 – $HOME/.sonar/cache"
notifications:
  email:
  - indra.basak1@gmail.com
  on_success: change
  on_failure: always
  use_notice: true
#env:
#  global:
#    secure: BsCA4MePKQniW6uI7XyFIQPQGo0sP/pjZhav5C8cdA6Z7hh4RLaI0cXo/M6H51R11f8in1B9+fs5wwDLPDdQelcRsigdm4T1BSyI7HmRnHxIRGJ463bxK5TOvVcMF07vWU1p9pUNfvCIqlUndU+O8luV5K5E8sRWd4kY/mEveG213mbiEm86jQE3JGWm3etLvIx20TrAEn86nX44LwOGFy2AgxcTkuzJRqGQVFnjg1/RfVu2v5foQT2ey4qLwTFQk/ShsN0FtlkqdS/ji3jSPiRVypJQA++ZkTwlnTyCwejRH1vHtnz3VsAgLqB/I92t+rvd6o6vDyCktK9DxebVyHbX16vk4HOpzQ5ENvRLq0UBfetqh16suraTb8X4eDxuVZ0/SwIUX+RQp9QvSSj3jgSEC5Enp30KBad0FCZM79xEtHZPn7S4pI0woNg4WACTzURd+KUOKA8nzxhDNyLNS9Yf5udNR7cgA3X/KMII4vSZ+tVFsILzwYQgqhypSgmnJg/iZ8mtaZUj6zuZvAWQK4367ZozYLQYQM+jrSYmqAoRJWzH4rIO25vt3Vkb3Fdg2VF9TVgolAPzzjLgYla9j9+g8Pt885/jHlT9CumMIKege/Chieig732h12aVtdY8PuXZ5jIoiApfk+R5BtixniTOd4aE9xXSkTg8ge5MTOM=
