apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-prom-config
  namespace: example
data:
  application-deployed.yml: |+
    logging:
      request:
        verbose: true

  prometheus.yml: |+
    startDelaySeconds: 0
    hostPort: 127.0.0.1:8888
    ssl: false
    lowercaseOutputName: false
    lowercaseOutputLabelNames: false
    rules:
      - pattern: ".*"

  env: |+
    JAVA_OPTS=" \
            -Dcom.sun.management.jmxremote=true \
            -Dcom.sun.management.jmxremote.local.only=true \
            -Dcom.sun.management.jmxremote.port=8888 \
            -Dcom.sun.management.jmxremote.rmi.port=8888 \
            -Dcom.sun.management.jmxremote.ssl=false \
            -Dcom.sun.management.jmxremote.authenticate=false
            -javaagent:/usr/local/example/bin/jmx_prometheus_javaagent.jar=8082:/usr/local/example/config/prometheus.yml"

