apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-prom
  namespace: example
spec:
  selector:
    matchLabels:
      app: spring-prom-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-prom-app
    spec:
      containers:
      - name: spring-prom-app
        image: basaki/spring-k8s-prometheus:1.0.0
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: deployed
        ports:
          - containerPort: 8080
            name: server
          - containerPort: 8081
            name: management
        volumeMounts:
          - name: spring-prom-config
            mountPath: /usr/local/iovation/example/config/application-deployed.yml
            subPath: application-deployed.yml # application yml
            readOnly: true
      volumes:
        - name: spring-prom-config
          configMap:
            name: spring-prom-config