apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-prom
  namespace: example
  labels:
    app: spring-prom-app
spec:
  namespaceSelector:
    matchNames:
      - example
  selector:
    matchLabels:
      app: spring-prom-app
  endpoints:
    - port: prom-agent
      path: /metrics
    - port: prom-jmx
      path: /metrics