apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana
spec:
  selector:
    matchLabels:
      app: grafana-app
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
        - name: grafana-app
          image: grafana/grafana:6.2.2
          env:
              # The following env variables are required to make Grafana accessible via
              # the kubernetes api-server proxy.
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: grafana-storage
              mountPath: /var
      volumes:
        - name: grafana-storage
          emptyDir: {}